apps/order/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('order/alone/', views.OrderView.as_view(), name='order'),
    path('order/connect_group/', views.OrderConnectGroupView.as_view(), name='order_connect_group'),
    path('order/create_group/', views.OrderCreateGroupView.as_view(), name='order_create_group'),
    path('order/create_group/edit/<int:pk>/', views.OrderEditGroupView.as_view(), name='order_group_edit'),
    path('order/create_group/delete/<int:pk>/', views.OrderDeleteGroupView.as_view(), name='order_group_delete'),
    path('order/create_group/leave/<int:pk>/', views.OrderLeaveGroupView.as_view(), name='order_group_leave'),
    path('order/per_day/', views.OrderPerDayView.as_view(), name='order_per_day'),
    path('order/delete/<int:pk>/', views.OrderDeleteView.as_view(), name='order_delete'),
    path('order/edit/<int:pk>/', views.OrderEditView.as_view(), name='order_edit'),

    path('block-list/', views.BlockListView.as_view()),
    path('room-list/', views.RoomListView.as_view()),
    path('placement-group-list/', views.PlacementGroupListView.as_view()),

    path('order-list/', views.OrderListView.as_view(), name='order_list'),
    path('eat/', views.EatView.as_view(), name='eat'),
    path('transfer/', views.TransferView.as_view(), name='transfer'),
    path('transfer/delete/<int:pk>/', views.TransferDeleteView.as_view(), name='transfer_delete'),

    path('event-request/', views.EventRequestListView.as_view(), name='event_request'),
    path('event-request/create/', views.EventRequestCreateView.as_view(), name='event_request_create'),
    path('event-request/edit/<int:id>/', views.EventRequestEditView.as_view(), name='event_request_edit'),
    path('event-request/thanks/', views.EventRequestThanksView.as_view(), name='event_request_thanks'),
]

uralcon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

from apps.users import urls as users_urls
from apps.order import urls as order_urls

urlpatterns = [
    path('', RedirectView.as_view(url='/order/order/alone'), name='index-url'),
    path('order/', include(order_urls)),
    path('users/', include(users_urls)),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from functools import reduce

from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse

from dynamic_preferences.registries import global_preferences_registry


global_preferences = global_preferences_registry.manager()


class UserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The Email must be set')

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField('Эл. почта', max_length=255, unique=True,)
    vk_id = models.CharField('ВКонтакте ID', max_length=50, blank=True)
    nickname = models.CharField('Никнэйм', max_length=50, blank=True)
    birth_date = models.DateField('Дата рождения', null=True, blank=False)
    city = models.CharField('Город', max_length=50, blank=False)
    photo = models.ImageField('Фотография для бейджа', upload_to='badge_photo/', blank=True)
    children_info = models.TextField('Информация о детях', blank=True)
    charge_person = models.ForeignKey(to='User', verbose_name='Информация об ответственном лице',
                                      blank=True, null=True, on_delete=models.SET_NULL)
    addition_info = models.TextField('Дополнительная информация (для модераторов)', blank=True)
    discount = models.IntegerField('Скидка', default=0, help_text='Указывается в рублях')

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['password',]

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ['last_name']

    def __str__(self):
        return f"{self.first_name} {self.last_name}" if self.last_name else self.email

    def get_absolute_url(self):
        return reverse('user_profile')

    def get_order(self):
        has_group = self.has_group()

        if len(self.order_set.all()) > 0:
            order = self.order_set.all()[0]
        elif has_group and len(has_group.placement_group.autor.order_set.all()) > 0:
            order = self.has_group().placement_group.autor.order_set.all()[0]
        else:
            return None

        if order.order_type == 'day_p':
            name = order.get_penetration_type().title
        else:
            name = f"{order.room.block.name}, {order.room.room_number}" if order.room else f"{order}"

        price_by_people = [{
            'name': u,
            'place': u.get_human_place_type(),
            'price': u.get_price()
        } for u in (order.userorder_set.all() \
                    if order.room and order.room.is_luxary \
                    else order.userorder_set.filter(user=self))]

        price_by_people.extend([{
            'name': ch,
            'place': ch.get_human_place_type(),
            'price': ch.get_price()
        } for ch in (order.childrenorder_set.all() \
                     if order.room and order.room.is_luxary \
                     else order.childrenorder_set.filter(children__user=self))])

        return {
            'name': name,
            'total_price': order.get_base_price(),
            'price_by_people': price_by_people,
            'order': order
        }

    def get_eat_amount(self):
        user_eat_orders = self.eatorder_set.all()
        return reduce(
            lambda x, y: (x.eat_order_price() if hasattr(x, 'eat_order_price') else x) + y.eat_order_price(),
            user_eat_orders, 0
        ) if user_eat_orders else 0

    def get_room_amount(self, total=False):
        try:
            order = self.get_order()['order']
        except (IndexError, TypeError):
            return 0

        # Если чувак владелец группы и снял люкс, то возвращаем полную стоимость заказа
        if self.has_group_owner() and order.room.is_luxary or total:
            return order.get_base_price() - self.discount

        # Если чувак состоит в группе, то все сильно уложняется
        if self.has_group():
            # Если это люкс, то оплата ложится на автора бронирования
            if order.room.is_luxary:
                return 0

            my_order = list(
                filter(
                    lambda u: u.user.pk is self.pk,
                    order.userorder_set.all()
                )
            )

            if not my_order:
                return 0

            price = my_order[0].get_price()

            for childorder in order.childrenorder_set.all():
                if childorder.children.user.pk is self.pk:
                    price += childorder.get_price()

            if order.without_other_mat_people and order.user.pk is self.pk:
                price += global_preferences['prices__price_for_alone_group']

            return price - self.discount

        return order.get_base_price() - self.discount

    def get_total_amount(self):
        return self.get_eat_amount() + self.get_room_amount()

    def has_group(self):
        if len(self.membership_set.all()) > 0:
            return self.membership_set.all()[0]
        else:
            return None

    def has_group_owner(self):
        if self.placementgroup_set.all():
            return self.placementgroup_set.all()[0]
        else:
            return None


class Children(models.Model):
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    age = models.IntegerField('Возраст (полных лет)', validators=[
        MaxValueValidator(17),
        MinValueValidator(0)
    ])
    name = models.CharField('ФИО ребенка', max_length=255, default='')

    class Meta:
        verbose_name = 'Ребенок'
        verbose_name_plural = 'Дети'

    def __str__(self):
        return f"{self.name} ({self.age} лет)"

    def get_discount(self):
        if self.age <= 7:
            return global_preferences['children_contribution__children_up_to_7_alone']

        if self.age > 7 and self.age <= 12:
            return global_preferences['children_contribution__children_7_12']

        if self.age > 12 and self.age <= 16:
            return global_preferences['children_contribution__children_13_16']

        return 0

apps/order/forms.py
from django import forms
from .models import EventRequest


class EventRequestForm(forms.ModelForm):
    class Meta:
        model = EventRequest
        exclude = ['user', 'is_accepted']

uralcon/templates/order/_base_order.html
{% extends "_base.html" %}

{% load static %}

{% block content %}
<div>
    <h1 class="title is-1">Бронирование билетов</h1>

    {% if can_order and not order_stop %}
        <div class="tag is-warning subtitle">
            Если вы хотите приехать на фестиваль с детьми, то&nbsp;<a href="{% url 'user_children' %}">укажите их в профиле</a>
        </div>
    {% endif %}

    {% if not request.user.order_set.all and not request.user.has_group %}
    <div class="tabs">
        <ul>
            <li{% if '/alone/' in request.META.PATH_INFO %} class="is-active"{% endif %}>
                <a href="{% url 'order' %}">Поселиться самостоятельно</a>
            </li>
            <li{% if '/connect_group/' in request.META.PATH_INFO %} class="is-active"{% endif %}>
                <a href="{% url 'order_connect_group' %}">Присоединиться к группе поселения</a>
            </li>
            <li{% if '/create_group/' in request.META.PATH_INFO %} class="is-active"{% endif %}>
                <a href="{% url 'order_create_group' %}">Создать группу поселения</a>
            </li>
            <li{% if '/per_day/' in request.META.PATH_INFO %} class="is-active"{% endif %}>
                <a href="{% url 'order_per_day' %}">Без поселения</a>
            </li>
        </ul>
    </div>
    {% endif %}

    <div class="alone">
        <div class="columns">
            <div class="column is-8">

                {% if order_stop %}
                    {% include 'order/snippets/_order_stop.html' %}
                {% endif %}

                {% if request.user.has_group %}
                    {% include 'order/snippets/_has_group.html' with user=request.user order_stop=order_stop %}
                {% endif %}

                {% if request.user.get_order %}
                    {% include 'order/snippets/_user_order.html' with request=request without_other_mat_people=without_other_mat_people order_stop=order_stop %}
                {% endif %}

                {% if not order_stop %}
                    {% block center_column %}
                    {% endblock %}
                {% endif %}
            </div>
            {% if can_order %}
            <div class="column is-4">
                {% block right_column %}
                {% endblock %}
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

uralcon/templates/order/busorder_confirm_delete.html
{% extends "order/_base_order.html" %}

{% block content %}
    <form method="post">{% csrf_token %}
        <h3 class="title is-3">Вы уверены, что хотите отменить бронирование трансфера?</h3>
        <input type="submit" value="Да" class="button is-link">
    </form>
{% endblock %}

uralcon/templates/order/eat.html
{% extends "_base.html" %}

{% load humanize %}

{% block content %}
    <div class="content">
        <h1 class="title is-1">Заказ еды</h1>

        <div class="columns">
            <div class="column is-8">
                {% if order_stop %}
                    {% include 'order/snippets/_order_stop.html' %}
                {% endif %}

                {% if eat_order_status %}
                    <div class="notification {% if eat_order_status.status %}is-success{% else %}is-danger{% endif %}">
                        {{ eat_order_status.message }}
                    </div>
                {% endif %}

                <form method="post">
                    {% csrf_token %}
                    <table class="table">
                        <thead>
                                <tr>
                                    <th>Время подачи</th>
                                    <th>Цена</th>
                                    <th></th>
                                </tr>
                        </thead>
                        <tbody>
                            {% for eat in eat_types %}
                                <tr>
                                    <td>
                                        {{ eat.title }}
                                        {% if eat.user_has %}
                                            <span class="help is-success">Оформлено</span>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <span class="is-size-4">{{ eat.price|intcomma }} ₽</span>
                                    </td>
                                    <td>
                                        {% if not order_stop %}
                                            {% if eat.user_has %}
                                                <button type="submit" name="eat_type" value="{{ eat.name }}" class="button is-text">
                                                    Отказаться
                                                </button>
                                            {% else %}
                                                <button type="submit" name="eat_type" value="{{ eat.name }}" class="button is-link is-fullwidth is-outlined">
                                                    Заказать
                                                </button>
                                            {% endif %}
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </form>
                <div class="selected-time box">
                    <div class="media">
                        <div class="media-content">
                            <div class="help">Итого к оплате за питание:</div>
                            <div>
                                <span class="is-size-1 has-text-grey">{{ request.user.get_eat_amount|intcomma }}</span><span class="is-size-4 has-text-grey">₽</span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="notification is-info">Для детей питание заказывайте по приезду при получении бейджа.</div>
            </div>
        </div>
    </div>
{% endblock %}

uralcon/templates/order/event_request_create.html
{% extends "_base.html" %}

{% load widget_tweaks %}

{% block content %}
    <div class="columns">
        <div class="column is-6">
            <div class="content">
                <h1 class="title is-1">Заявка на проведение мероприятия</h1>

                <form method="post">
                    {% csrf_token %}

                    <div class="field">
                        <label class="label">{{ form.name.label_tag }}</label>
                        <div class="control">
                            {% render_field form.name class="input" %}
                        </div>
                        {% if form.name.errors %}<div class="help is-danger">{{form.name.errors}}</div>{% endif %}
                    </div>

                    <div class="field">
                        <label class="label">{{ form.contact_info.label_tag }}</label>
                        <div class="control">
                            {% render_field form.contact_info class="input" rows="3" %}
                            <p class="help">{{ form.contact_info.help_text|safe }}</p>
                        </div>
                        {% if form.contact_info.errors %}<div class="help is-danger">{{form.contact_info.errors}}</div>{% endif %}
                    </div>

                    <div class="field">
                        <label class="label">{{ form.description.label_tag }}</label>
                        <div class="control">
                            {% render_field form.description class="textarea" rows="3" %}
                            <p class="help">{{ form.description.help_text|safe }}</p>
                        </div>
                        {% if form.description.errors %}<div class="help is-danger">{{form.description.errors}}</div>{% endif %}
                    </div>

                    <div class="field">
                        <label class="label">{{ form.public_description.label_tag }}</label>
                        <div class="control">
                            {% render_field form.public_description class="textarea" rows="3" %}
                            <p class="help">{{ form.public_description.help_text|safe }}</p>
                        </div>
                        {% if form.public_description.errors %}<div class="help is-danger">{{form.public_description.errors}}</div>{% endif %}
                    </div>

                    <div class="field">
                        <label class="label">{{ form.what_need.label_tag }}</label>
                        <div class="control">
                            {% render_field form.what_need class="textarea" rows="3" %}
                            <p class="help">{{ form.what_need.help_text|safe }}</p>
                        </div>
                        {% if form.what_need.errors %}<div class="help is-danger">{{form.what_need.errors}}</div>{% endif %}
                    </div>

                    <div class="field">
                        <label class="label">{{ form.what_has.label_tag }}</label>
                        <div class="control">
                            {% render_field form.what_has class="textarea" rows="3" %}
                            <p class="help">{{ form.what_has.help_text|safe }}</p>
                        </div>
                        {% if form.what_has.errors %}<div class="help is-danger">{{form.what_has.errors}}</div>{% endif %}
                    </div>

                    <div class="field">
                        <label class="label">{{ form.placement.label_tag }}</label>
                        <div class="control">
                            {% render_field form.placement class="textarea" rows="3" %}
                            <p class="help">{{ form.placement.help_text|safe }}</p>
                        </div>
                        {% if form.name.errors %}<div class="help is-danger">{{form.placement.errors}}</div>{% endif %}
                    </div>

                    <div class="field">
                        <label class="label">{{ form.time.label_tag }}</label>
                        <div class="control">
                            {% render_field form.time class="textarea" rows="3" %}
                            <p class="help">{{ form.time.help_text|safe }}</p>
                        </div>
                        {% if form.time.errors %}<div class="help is-danger">{{form.time.errors}}</div>{% endif %}
                    </div>

                    <div class="field">
                        <label class="label">{{ form.need_charter.label_tag }}</label>
                        <div class="control">
                            {% render_field form.need_charter class="textarea" rows="3" %}
                            <p class="help">{{ form.need_charter.help_text|safe }}</p>
                        </div>
                        {% if form.need_charter.errors %}<div class="help is-danger">{{form.need_charter.errors}}</div>{% endif %}
                    </div>

                    <button type="submit" class="button is-link">
                        {% if form.initial.id %}
                            Сохранить изменения
                        {% else %}
                            Отправить заявку
                        {% endif %}
                    </button>
                </form>

                <!--<div class="message is-info">-->
                    <!--<div class="message-body">-->
                        <!--Ваша заявка на рассмотрении. Как только администрация примет выводы относительно заявки, мы с вами свяжемся.-->
                    <!--</div>-->
                <!--</div>-->
            </div>
        </div>
    </div>
{% endblock %}

uralcon/templates/order/order_confirm_delete.html
{% extends "order/_base_order.html" %}

{% block content %}
    <form method="post">{% csrf_token %}
        <h3 class="title is-3">Вы уверены, что хотите отменить бронирование?</h3>
        <input type="submit" value="Да" class="button is-link">
    </form>
{% endblock %}

uralcon/templates/order/order_order.html
{% extends "order/_base_order.html" %}

{% load static %}

{% block center_column %}
    {% if can_order %}
        <script type="text/javascript">
            {% if user.has_group_owner %}
            const groupCount = {{ user.has_group.placement_group.get_all_participant|length }};
            {% else %}
            const groupCount = {{ user.children_set.all|length }} + 1;
            {% endif %}

            const hasGroupOwner = {% if user.has_group_owner %}true{% else %}false{% endif %};
            const withoutOtherMatPeople = parseInt({{without_other_mat_people}});
            const discount = {
                children_up_to_7_alone: parseInt({{discount.children_up_to_7_alone}}),
                children_7_12: parseInt({{discount.children_7_12}}),
                children_13_16: parseInt({{discount.children_13_16}}),
            };
            var roomClass = 'standart';
            var totalPrice = 0;
            var selectedRoom = null;
            var instance = null;
        </script>
        <h4 class="title is-4">Выберите тип номера:</h4>

        <form method="post" id="order-room">
            {% csrf_token %}

            {% if user.has_group_owner %}
            <input type="hidden" value="{{ user.has_group.placement_group.pk }}" name="placement_group">
            {% endif %}

            <div class="tabs is-toggle is-fullwidth" id="room-type-choose">
                <ul>
                    <li class="is-active" data-class="standart">
                        <a>Стандарт</a>
                    </li>
                    <li data-class="luxary">
                         <a>Люкс</a>
                    </li>
                </ul>
            </div>

            <div class="field">
                <label class="label">Корпус:</label>
                <div class="control">
                    <div class="select is-fullwidth">
                        <select id="block-select">
                        </select>
                    </div>
                </div>
            </div>

            <div class="field hidden" id="room-select-block">
                <label class="label">Номер:</label>
                <div class="control">
                    <div class="select is-fullwidth">
                        <select id="room-select" name="room">
                        </select>
                    </div>
                </div>
            </div>
            <br>

            <div id="resettlement-block" class="hidden">
                <h4 class="title is-4">Расселение:</h4>
                <table class="table is-striped is-hoverable is-fullwidth" >
                    {% for user in request.user.has_group_owner.get_all_participant %}
                        {% include 'order/snippets/_ressetlement_item.html' with user=user request=request %}
                    {% empty %}
                        {% include 'order/snippets/_ressetlement_item.html' with user=request.user request=request %}
                        {% for children in request.user.children_set.all %}
                            {% include 'order/snippets/_ressetlement_item.html' with user=children request=request %}
                        {% endfor %}
                    {% endfor %}
                </table>
            </div>

            {% if user.has_group_owner %}
            <div class="field hidden" id="without_other_mat_people-block">
                <div class="control">
                    <label for="without_other_mat_people" class="checkbox">
                        <input type="checkbox" value="1" name="without_other_mat_people" id="without_other_mat_people" class="checkbox">
                        Доплатить {{without_other_mat_people}}₽ за отсутствие пеночников
                    </label>
                    <p class="help">
                        Если вы не хотите, чтобы к вам в номер подселялись другие участники на пенках, то вы можете доплатить {{without_other_mat_people}}₽

                    </p>
                </div>
            </div>
            {% endif %}

            <div class="notification is-danger hidden" id="order-error-message"></div>

            <div class="field">
                <div class="control">
                    <input type="submit" value="Забронировать" class="button is-link" id="">
                </div>
            </div>

            {% include 'order/snippets/_room_amount.html' with user=request.user %}
        </form>
    {% endif %}
{% endblock %}

{% block right_column %}
    <h4 class="title is-h4">Корпуса</h4>
    <div id="blocks-list">

    </div>
{% endblock %}

uralcon/templates/order/order_order_edit.html
{% extends "_base.html" %}

{% load static %}

{% block content %}
<div>
    <h1 class="title is-1">Редактирование расселения в номере</h1>

    <div class="alone">
        <div class="columns">
            <div class="column is-8">
                <script type="text/javascript">
                    {% if user.has_group_owner %}
                    const groupCount = {{ user.has_group.placement_group.get_all_participant|length }};
                    const hasGroupOwner = true;
                    {% else %}
                    const groupCount = {{ user.children_set.all|length }} + 1;
                    const hasGroupOwner = false;
                    {% endif %}

                    const withoutOtherMatPeople = parseInt({{without_other_mat_people}});
                    const discount = {
                        children_up_to_7_alone: parseInt({{discount.children_up_to_7_alone}}),
                        children_7_12: parseInt({{discount.children_7_12}}),
                        children_13_16: parseInt({{discount.children_13_16}}),
                    };
                    var roomClass = 'standart';
                    var totalPrice = 0;
                    var selectedRoom = {{selectedRoom|safe}};
                    var instance = {{instance.pk}};
                </script>

                <form method="post" id="order-room">
                    {% csrf_token %}
                    <input type="hidden" name="room" value="{{instance.room.pk}}" />

                    {% if user.has_group_owner %}
                    <input type="hidden" value="{{ user.has_group.placement_group.pk }}" name="placement_group">
                    {% endif %}

                    <div id="resettlement-block" class="">
                        <h4 class="title is-4">Расселение:</h4>
                        <table class="table is-striped is-hoverable is-fullwidth" >
                            {% for user in request.user.has_group_owner.get_all_participant %}
                                {% include 'order/snippets/_ressetlement_item.html' with user=user request=request %}
                            {% empty %}
                                {% include 'order/snippets/_ressetlement_item.html' with user=request.user request=request %}
                                {% for children in request.user.children_set.all %}
                                    {% include 'order/snippets/_ressetlement_item.html' with user=children request=request %}
                                {% endfor %}
                            {% endfor %}
                        </table>
                    </div>

                    {% if user.has_group_owner %}
                    <div class="field" id="without_other_mat_people-block">
                        <div class="control">
                            <label for="without_other_mat_people" class="checkbox">
                                <input type="checkbox" value="1" name="without_other_mat_people"
                                       id="without_other_mat_people" class="checkbox"
                                       {% if instance.without_other_mat_people %}checked="true"{% endif %}>
                                Доплатить {{without_other_mat_people}}₽ за отсутствие пеночников
                            </label>
                            <p class="help">
                                Если вы не хотите, чтобы к вам в номер подселялись другие участники на пенках, то вы можете доплатить {{without_other_mat_people}}₽
                            </p>
                        </div>
                    </div>
                    {% endif %}

                    <div class="notification is-danger hidden" id="order-error-message"></div>
                    <br>

                    <div class="field">
                        <div class="control">
                            <input type="submit" value="Сохранить изменения" class="button is-link" id="">
                            <a href="{% url 'order' %}" class="button is-white">Вернуться</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

uralcon/templates/order/placementgroup_confirm_delete.html
{% extends "order/_base_order.html" %}

{% block content %}
    <form method="post">{% csrf_token %}
        <h3 class="title is-3">Вы уверены, что хотите удалить группу «{{ object.name }}»?</h3>
        <p>
            С учетом вас, в группе состоят {{object.users.count}} человек.
        </p>
        <input type="submit" value="Да" class="button is-link">
    </form>
{% endblock %}